---
collections:
  - name: "https://github.com/FabOS-AI/fabos-slm-dc-docker"
    type: git
    version: main

roles:
  - src: "git+https://github.com/FabOS-AI/molecule_libvirt.git"
    scm: git
    version: main
    name: molecule_libvirt