---
- name: Converge - Leave Swarm and Uninstall docker
  hosts: all:!hypervisor
  gather_facts: yes
  vars:
    ansible_libvirt_uri: >-
      {% if hostvars[groups['hypervisor'] | first].ansible_connection == 'ssh' %}qemu+ssh://{{ hostvars[groups['hypervisor'] | first].ansible_user }}@{{ hostvars[groups['hypervisor'] | first].ansible_host }}/system{% else %}qemu:///system{% endif %}
    ansible_connection: "community.libvirt.libvirt_qemu"
  become: yes
  serial: "{{ lookup('env', 'ANSIBLE_SERIAL') }}"
#  collections:
#    - fabos.docker
  tasks:
    - name: "Include fabos.docker_swarm.setup - uninstall"
      include_role:
        name: setup
        tasks_from: uninstall.yml

    - name: "Include fabos.docker.setup - uninstall"
      include_role:
        name: fabos.docker.setup
        tasks_from: uninstall.yml